name = "edge-zero-trust-proxy"
main = "build/index.js"
compatibility_date = "2026-08-15"
compatibility_flags = ["global_fetch_strictly_public"]

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[ai]
binding = "AI"
remote = true

[vars]
UPSTREAM_URL = "http://127.0.0.1:8788" # Backend URL for accessing API
AI_MODEL = "@cf/meta/llama-4-scout-17b-16e-instruct"
TEAM_DOMAIN = "https://team-domain.cloudflareaccess.com" # Your Cloudflare Zero Trust team domain
AUD_TAG = "BLANK" # Your Cloudflare Zero Trust AUD tag after adding proxy as an application to Zero Trust